imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
        name: MOCKSESSID
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

#Turn on Basic Auth for testing,
security:
    firewalls:
        login:
            security: true

liip_functional_test: ~

# We are going to use MySQL for our tests
#doctrine:
#    dbal:
#        default_connection: default
#        connections:
#            default:
#                driver:   pdo_sqlite
#                path:     %kernel.cache_dir%/test.db
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     '%database_host%'
        port:     '%database_port%'
        dbname:   '%database_name%_test'
        user:     '%database_user%'
        password: '%database_password%'
        charset:  UTF8