imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ['%locale%'] }
    secret:          '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  '%locale%'
    trusted_hosts:   ~ # TODO: use Nelmio CORS
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     '%database_host%'
        port:     '%database_port%'
        dbname:   '%database_name%'
        user:     '%database_user%'
        password: '%database_password%'
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
#        entity_managers:
#            default:
#        mappings: # http://symfony.com/doc/master/bundles/StofDoctrineExtensionsBundle/index.html
#            gedmo_translatable:
#                type: annotation
#                prefix: Gedmo\Translatable\Entity
#                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
#                alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
#                is_bundle: false
#            gedmo_translator:
#                type: annotation
#                prefix: Gedmo\Translator\Entity
#                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
#                alias: GedmoTranslator # (optional) it will default to the name set for the mapping
#                is_bundle: false
#            gedmo_loggable:
#                type: annotation
#                prefix: Gedmo\Loggable\Entity
#                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
#                alias: GedmoLoggable # (optional) it will default to the name set for the mappingmapping
#                is_bundle: false
#            gedmo_tree:
#                type: annotation
#                prefix: Gedmo\Tree\Entity
#                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
#                alias: GedmoTree # (optional) it will default to the name set for the mapping
#                is_bundle: false

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            timestampable: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host:      '%mailer_host%'
    username:  '%mailer_user%'
    password:  '%mailer_password%'
    spool:     { type: memory }

# Lexik JWT configuration
lexik_jwt_authentication:
    private_key_path: '%jwt_private_key_path%'
    public_key_path:  '%jwt_public_key_path%'
    pass_phrase:      '%jwt_key_pass_phrase%'
    token_ttl:        '%jwt_token_ttl%'
    user_identity_field: username

sensio_framework_extra:
    request: { converters: true }

# Bundle FOSRest
fos_rest:
    versioning:
        enabled: true
        default_version: v1
        resolvers:
            query:
                enabled: true
                parameter_name: version
    disable_csrf_role: ROLE_API
    param_fetcher_listener:
      enabled: true
      force: true
    body_listener: true
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors
    format_listener:
        rules:
            fallback_format: json
            prefer_extension: false
            priorities: [json, xml, html]
            prefer_extension: false
    serializer:
      serialize_null: true
    view:
        view_response_listener: 'force' #false
        serialize_null: true
        formats:
            xml: true
            json: true
        mime_types:
            json: ['application/json', 'application/x-json']
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json

nelmio_api_doc:
    documentation:
        info:
            title: "SIPMEL"
            description: "Simplifying control over communication"
            version: 1.0.0
        securityDefinitions: #securitySchemes
            api_key:
                type: apiKey
                description: json Web Token
                name:  Authorization
                in: header
        security:
            - api_key: []

    routes:
        path_patterns: # an array of regexps
            - ^/API/[^Doc]

#    name: "SIPMEL"
#    sandbox:
#        enabled: true
#        authentication:
#            delivery: http # When choosing an http delivery, name defaults to Authorization, and the header value will automatically be prefixed by the corresponding type (ie. Basic or Bearer).
#            type:     bearer # pr basic
#        body_format:
#            formats:
#                # Defaults:
#                - json
#                - xml
#             default_format: json

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"