app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#For Testing
api_basic_auth_login_check:
    path: /API/Basic/login_check

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /API/Doc

REST_User:
    resource: "@AppBundle/Controller/API/UserController.php"
    type: rest
    prefix: /API/{version}/User
    #name_prefix:  api_user_
    requirements:
        version: v1

REST_Variable:
    resource: "@AppBundle/Controller/API/VariableController.php"
    type: rest
    prefix: /API/{version}/Variable
    #name_prefix:  api_user_
    requirements:
        version: v1

REST_Category:
    resource: "@AppBundle/Controller/API/CategoryController.php"
    type: rest
    prefix: /API/{version}/Category
    #name_prefix:  api_user_
    requirements:
        version: v1

REST_Category_Content:
    resource: "@AppBundle/Controller/API/ContentController.php"
    type: rest
#    prefix: /API/{version}/Category/{category}/Content
    prefix: /API/{version}/Content
    #name_prefix:  api_user_
    requirements:
        version: v1

REST_Bucket:
    resource: "@AppBundle/Controller/API/BucketController.php"
    type: rest
    prefix: /API/{version}/Bucket
    #name_prefix:  api_user_
    requirements:
        version: v1