app:
    resource: "@AppBundle/Controller/"
    type:     annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /API/Doc

REST_User:
    resource: "@AppBundle/Controller/API/UserController.php"
    type: rest
    prefix: /API/{version}/User
    #name_prefix:  api_user_
    requirements:
      version: v1