app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#For Testing
api_basic_auth_login_check:
    path: /API/Basic/login_check

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /API/Doc

REST_User:
    resource: "@AppBundle/Controller/API/UserController.php"
    type: rest
    prefix: /API/{version}/User
    #name_prefix:  api_user_
    requirements:
        version: v1