# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        database_users:
            entity: { class: AppBundle:User , property: username }


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_user:
            pattern: ^/API/v[0-9]+/User/(Token/New|ForgotPassword|Register)
            security: false
        api_doc:
            pattern: ^/API/Doc
            security: false
        api:
            pattern:   ^/API
            anonymous: false
            http_basic: ~
            stateless: true
            guard:
                authenticators:
                    - AppBundle\Security\JwtAuthenticator

    access_control:
        - { path: ^/API/v[0-9]+/User/Token/New, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/API/v[0-9]+/User/ForgotPassword, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/API/v[0-9]+/User/Register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/API/Doc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/API/v[0-9]+/User, roles: ROLE_USER }
        - { path: ^/API, roles: ROLE_API }


        # Example for resources with JSON Web Token authentication
        #- { path: ^/api/secure, roles: ROLE_ADMIN }

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    role_hierarchy:
        ROLE_API:         [] #Send and manage lists
        ROLE_ADMIN:       [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]